language: java
install: mvn install
env:
  - DOCKER_USERNAME="ob7777"

services:
- docker

script:
- docker login -u "$DOCKER_USERNAME" -p "$pass"
- docker build -t ci-spring-showcase .
- docker images
- docker tag ci-spring-showcase $DOCKER_USERNAME/ci-spring-showcase
- docker push $DOCKER_USERNAME/ci-spring-showcase:$(bash cat version)