language: java
install: mvn install

services:
- docker

script:
- docker login -u "ob7777" -p "$pass"
- docker build -t ci-spring-showcase .
- docker images
- docker tag ci-spring-showcase $DOCKER_USERNAME/ci-spring-showcase
- docker push $DOCKER_USERNAME/ci-spring-showcase