language: java
sudo: required
install: mvn install

env:
  - DOCKER_USERNAME="ob7777"

services:
- docker

script:
- docker login -u "$DOCKER_USERNAME" -p "$pass"
- docker build -t ci-spring-showcase .
- sh docker.sh